name: Publish New Release to PyPI
on:
  release:
    types: [created]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install and configure Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint test
        run: |
          poetry run flake8
      - name: Unit and functional tests
        run: |
          poetry run pytest
      - name: Build
        run: |
          poetry build
      - name: Publish
        run: |
          poetry publish -u __token__ -p ${{ secrets.PYMONGOIM_PYPI_TOKEN }}
